using CompetencyEvaluator.Shared;
using CompetencyEvaluator.Categories;
using CompetencyEvaluator.Genders;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using CompetencyEvaluator.Permissions;
using CompetencyEvaluator.Athletes;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using CompetencyEvaluator.Shared;

namespace CompetencyEvaluator.Athletes
{
    public class AthletesAppService : AthletesAppServiceBase, IAthletesAppService
    {
        //<suite-custom-code-autogenerated>
        public AthletesAppService(IAthleteRepository athleteRepository, AthleteManager athleteManager, IDistributedCache<AthleteExcelDownloadTokenCacheItem, string> excelDownloadTokenCache, IRepository<Gender, Guid> genderRepository, IRepository<Category, Guid> categoryRepository)
            : base(athleteRepository, athleteManager, excelDownloadTokenCache, genderRepository, categoryRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}