using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace CompetencyEvaluator.Categories
{
    public class Category : CategoryBase
    {
        //<suite-custom-code-autogenerated>
        protected Category()
        {

        }

        public Category(Guid id, string name, int? maxAge = null)
            : base(id, name, maxAge)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}