using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace CompetencyEvaluator.Athletes
{
    public class AthleteManager : AthleteManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AthleteManager(IAthleteRepository athleteRepository)
            : base(athleteRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}