using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace CompetencyEvaluator.TypeRules
{
    public class TypeRule : TypeRuleBase
    {
        //<suite-custom-code-autogenerated>
        protected TypeRule()
        {

        }

        public TypeRule(Guid id, string name)
            : base(id, name)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}