using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace CompetencyEvaluator.TypeRules
{
    public class TypeRuleManager : TypeRuleManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TypeRuleManager(ITypeRuleRepository typeRuleRepository)
            : base(typeRuleRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}