using CompetencyEvaluator.Athletes;
using CompetencyEvaluator.Athletes;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace CompetencyEvaluator.Evaluation1s
{
    public class Evaluation1 : Evaluation1Base
    {
        //<suite-custom-code-autogenerated>
        protected Evaluation1()
        {

        }

        public Evaluation1(Guid id, Guid athleteId, double criterio_1_R1, double criterio_1_R2, double criterio_2_R1, double criterio_2_R2, double criterio_3_R1, double criterio_3_R2, double criterio_4_R1, double criterio_4_R2, double resultado_R1, double resultado_R2)
            : base(id, athleteId, criterio_1_R1, criterio_1_R2, criterio_2_R1, criterio_2_R2, criterio_3_R1, criterio_3_R2, criterio_4_R1, criterio_4_R2, resultado_R1, resultado_R2)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}