using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace CompetencyEvaluator.Evaluation1s
{
    public class Evaluation1Manager : Evaluation1ManagerBase
    {
        //<suite-custom-code-autogenerated>
        public Evaluation1Manager(IEvaluation1Repository evaluation1Repository)
            : base(evaluation1Repository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}