using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace CompetencyEvaluator.Genders
{
    public class GenderManager : GenderManagerBase
    {
        //<suite-custom-code-autogenerated>
        public GenderManager(IGenderRepository genderRepository)
            : base(genderRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}